### ISSUE TITLE
地图没开放，怎么办呢。

### ISSUE THREAD

**Issue by iwh718** [DFocusFE/react-fengmap#1]
个人开发者。

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by leftstick** [comment]
蜂鸟地图都是商业用途的，一般场景是你们公司在帮助其他某个公司做一个需要集成室内地图的软件，你们公司要开一个蜂鸟地图的账号，并且付费提交你客户的物业平面图，由蜂鸟制作蜂鸟室内图之后交给们使用的。

所以如果你是独立开发者，就没什么可操作的空间了，只能拿蜂鸟官网示例几张图玩玩

**Comment by iwh718** [comment]
@leftstick  谢谢回复。使用esmap了。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
